@startuml
skinparam linetype ortho
skinparam ConditionEndStyle hline
skinparam ConditionStyle InsideDiamond
skinparam DefaultTextAlignment center
:Початок;
if (Exit button pressed) then (yes)
:end;
else 
    repeat
    if (Play pressed) then (yes)
    
    endif
    
    repeat while ()
endif
kill
@enduml